@hostAddress = https://localhost:7184

POST {{hostAddress}}/accounts/token
Accept: application/json
Content-Type: application/json
{
  "grant_type": "password",
  "user_name": "prem",
  "password": "123"
}
###


GET {{hostAddress}}/employees
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJzdWIiOiIxIiwicm9sZXMiOiJNYW5hZ2VyIiwiZXhwIjoxNzQxNDM5NjQ1LCJpc3MiOiJUcmFpbmluZ19BUEkiLCJhdWQiOiJUcmFpbmluZyJ9.dJPgkj3eV1zM3Vy0H5WylkCtGoKL0tlPs3squZAOHsU
###
